package com.emm.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

@DisableCachingByDefault(because = "Writing one small file is cheaper than a build cache round trip")
abstract class GenerateBuildInfoTask : DefaultTask() {

    @get:Input
    abstract val commitHash: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val full = normalizeCommitHash(commitHash.get())

        val packageDir = outputDirectory.get().asFile.resolve("com/emm/justchill")
        packageDir.mkdirs()
        packageDir.resolve("BuildInfo.kt").writeText(
            """
            |package com.emm.justchill
            |
            |// GENERATED by the generate<Variant>BuildInfo Gradle task from `git rev-parse HEAD`.
            |// DO NOT EDIT and DO NOT COMMIT — this file lives under build/ and is regenerated on build.
            |//
            |// `val`, deliberately NOT `const val`. A const is inlined into every call site, so a
            |// value that changes on every commit would change the ABI of everything that reads it
            |// and force those files to recompile on each build. A plain val compiles to a field
            |// plus a getter: the hash moves, the ABI does not. Do not "optimize" this into a const.
            |object BuildInfo {
            |    val commitHash: String = "$full"
            |}
            |
            """.trimMargin(),
        )
    }

    internal companion object {
        /**
         * The same literal as `:ui-android`'s `UNKNOWN_COMMIT_HASH`, duplicated because build-logic
         * is not on the app's compile classpath — the two cannot be one constant.
         */
        const val UNKNOWN_COMMIT = "unknown"

        private val FULL_SHA = Regex("[0-9a-f]{40}")

        /**
         * The value is interpolated straight into a Kotlin string literal, where a quote, a
         * backslash or the trailing newline `git` always prints would break the build in a file no
         * human ever opens.
         */
        fun normalizeCommitHash(raw: String): String {
            val trimmed = raw.trim().lowercase()
            return if (FULL_SHA.matches(trimmed)) trimmed else UNKNOWN_COMMIT
        }
    }
}
