package com.emm.buildlogic

import java.io.FileInputStream
import java.util.Properties
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Writes the iOS counterpart of Android's `BuildConfig.SUPABASE_*`.
 *
 * Android reads root supabase.properties through buildConfigField with ""-fallbacks. iOS has no
 * BuildConfig, so this generates a Kotlin constants object from the SAME root file into a build/
 * source dir that gets wired into iosMain. Secrets are never hardcoded and the output lives under
 * build/ (gitignored). When supabase.properties is absent (CI), the fields fall back to empty or
 * the localhost placeholder exactly like Android, so the app stays usable offline/anonymous.
 *
 * A typed task rather than an ad-hoc `doLast { }`: inputs and outputs are declared as properties, so
 * incrementality and configuration-cache compatibility come from the type instead of from
 * remembering not to capture script state in the action.
 */
abstract class GenerateIosSupabaseConfigTask : DefaultTask() {

    /** Root supabase.properties. Optional — absent on CI, where the fallbacks take over. */
    @get:InputFile
    @get:Optional
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val propertiesFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val props = Properties()
        val file = propertiesFile.asFile.orNull
        if (file != null && file.exists()) {
            FileInputStream(file).use(props::load)
        }

        // ios.* override first, then dev.* (parity with :androidApp's dev flavor). The iOS simulator
        // shares the host network, so localhost == host; dev.supabase.url uses 10.0.2.2 — the
        // Android-emulator host alias, which the simulator cannot resolve. The ios.* override lets
        // both clients target the SAME local stack through their own alias. SUPABASE_URL keeps the
        // empty -> localhost placeholder fallback that provideSupabaseClient() applies on Android;
        // the anon key falls back to dev.* and stays empty only when both are absent.
        val url = props.getProperty("ios.supabase.url", "")
            .ifBlank { props.getProperty("dev.supabase.url", "") }
            .ifBlank { "http://localhost:54321" }
        val anonKey = props.getProperty("ios.supabase.anonKey", "")
            .ifBlank { props.getProperty("dev.supabase.anonKey", "") }

        val packageDir = outputDirectory.get().asFile.resolve("com/emm/justchill")
        packageDir.mkdirs()
        packageDir.resolve("IosSupabaseConfig.kt").writeText(
            """
            |package com.emm.justchill
            |
            |// GENERATED by the generateIosSupabaseConfig Gradle task from root supabase.properties.
            |// DO NOT EDIT and DO NOT COMMIT — this file lives under build/ and is regenerated on build.
            |// iOS equivalent of Android's BuildConfig.SUPABASE_URL / SUPABASE_ANON_KEY.
            |internal object IosSupabaseConfig {
            |    const val SUPABASE_URL: String = ${url.toKotlinStringLiteral()}
            |    const val SUPABASE_ANON_KEY: String = ${anonKey.toKotlinStringLiteral()}
            |}
            |
            """.trimMargin(),
        )
    }

    /** Escapes a raw value so a quote or backslash in a key can never break compilation. */
    private fun String.toKotlinStringLiteral(): String =
        "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}") + "\""
}
