package com.emm.buildlogic

import java.io.FileInputStream
import java.util.Properties
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

abstract class GenerateIosSupabaseConfigTask : DefaultTask() {

    @get:InputFile
    @get:Optional
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val propertiesFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val props = Properties()
        val file = propertiesFile.asFile.orNull
        if (file != null && file.exists()) {
            FileInputStream(file).use(props::load)
        }

        // The ios.* key exists because dev.supabase.url holds 10.0.2.2, the Android-emulator host
        // alias, which the iOS simulator cannot resolve. The simulator shares the host network, so
        // the override lets both clients reach the SAME local stack through their own alias.
        val url = props.getProperty("ios.supabase.url", "")
            .ifBlank { props.getProperty("dev.supabase.url", "") }
            .ifBlank { "http://localhost:54321" }
        val anonKey = props.getProperty("ios.supabase.anonKey", "")
            .ifBlank { props.getProperty("dev.supabase.anonKey", "") }

        val packageDir = outputDirectory.get().asFile.resolve("com/emm/justchill")
        packageDir.mkdirs()
        packageDir.resolve("IosSupabaseConfig.kt").writeText(
            """
            |package com.emm.justchill
            |
            |// GENERATED by the generateIosSupabaseConfig Gradle task from root supabase.properties.
            |// DO NOT EDIT and DO NOT COMMIT — this file lives under build/ and is regenerated on build.
            |// iOS equivalent of Android's BuildConfig.SUPABASE_URL / SUPABASE_ANON_KEY.
            |internal object IosSupabaseConfig {
            |    const val SUPABASE_URL: String = ${url.toKotlinStringLiteral()}
            |    const val SUPABASE_ANON_KEY: String = ${anonKey.toKotlinStringLiteral()}
            |}
            |
            """.trimMargin(),
        )
    }

    private fun String.toKotlinStringLiteral(): String =
        "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}") + "\""
}
