package com.emm.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes `BuildInfo.kt`: the git commit the running app was built from.
 *
 * The app ships to exactly one device — the author's, daily, through Firebase App Distribution —
 * so "which build am I looking at?" is a question with no answer today: `versionName` is the
 * nearest release tag and stays identical across dozens of builds. The commit hash is the only
 * identifier that moves with the code.
 *
 * The hash arrives as a plain `@Input` string rather than being read here, so the configuration
 * cache can decide whether this task is up to date without running git during execution, and so
 * the task itself has no dependency on a git checkout being present.
 *
 * ### Known limitation: a dirty working tree
 *
 * `git rev-parse HEAD` names the last commit, not the bytes that were compiled. A build made with
 * uncommitted edits advertises a commit whose code it did not build, and the footer has no way to
 * say so. `git describe --dirty` is the usual mitigation and is deliberately NOT used: the
 * 40-hex-or-nothing rule in [normalizeCommitHash] would reduce a `-dirty` suffix to "unknown", and
 * widening that regex to admit the suffix is the one change that would make the generated file
 * unsafe again. The limitation is accepted. What ships through Firebase App Distribution is built
 * by CI from a pushed commit, so the tree is clean exactly where the hash is load-bearing; a dirty
 * local build is a build whose author already knows what is in it.
 *
 * A typed task rather than an ad-hoc `doLast { }`, for the same reason as
 * [GenerateIosSupabaseConfigTask]: inputs and outputs are declared as properties, so incrementality
 * and configuration-cache compatibility come from the type instead of from remembering not to
 * capture script state in the action.
 */
@CacheableTask
abstract class GenerateBuildInfoTask : DefaultTask() {

    /** Raw `git rev-parse HEAD` output, or [UNKNOWN_COMMIT] when git could not answer. */
    @get:Input
    abstract val commitHash: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val full = normalizeCommitHash(commitHash.get())

        val packageDir = outputDirectory.get().asFile.resolve("com/emm/justchill")
        packageDir.mkdirs()
        packageDir.resolve("BuildInfo.kt").writeText(
            """
            |package com.emm.justchill
            |
            |// GENERATED by the generate<Variant>BuildInfo Gradle task from `git rev-parse HEAD`.
            |// DO NOT EDIT and DO NOT COMMIT — this file lives under build/ and is regenerated on build.
            |//
            |// `val`, deliberately NOT `const val`. A const is inlined into every call site, so a
            |// value that changes on every commit would change the ABI of everything that reads it
            |// and force those files to recompile on each build. A plain val compiles to a field
            |// plus a getter: the hash moves, the ABI does not. Do not "optimize" this into a const.
            |object BuildInfo {
            |    val commitHash: String = "$full"
            |}
            |
            """.trimMargin(),
        )
    }

    internal companion object {
        /**
         * Stand-in when git cannot answer — a source tarball, a shallow export, no git on PATH.
         *
         * A sentinel, not a short hash: the footer matches this exact word and renders a distinct
         * "no commit" state instead of abbreviating it. `:ui-android`'s `UNKNOWN_COMMIT_HASH` holds
         * the same literal on the consuming side — build-logic is not on the app's compile
         * classpath, so they cannot be one constant.
         *
         * Nothing links them. build-logic has no test source set, so editing this word compiles,
         * ships, and leaves every suite green while a git-less build renders "Commit unknow" with
         * a copy button. If you change it, change `UNKNOWN_COMMIT_HASH` by hand.
         */
        const val UNKNOWN_COMMIT = "unknown"

        private val FULL_SHA = Regex("[0-9a-f]{40}")

        /**
         * Reduces anything that is not a full lowercase SHA-1 to [UNKNOWN_COMMIT].
         *
         * This is what keeps the generated file compilable: the value is interpolated straight into
         * a Kotlin string literal, and a quote, a backslash or the trailing newline `git` always
         * prints would break the build in a file no human ever opens. Rejecting outright beats
         * escaping — a hash is either 40 hex characters or it is not a hash.
         */
        fun normalizeCommitHash(raw: String): String {
            val trimmed = raw.trim().lowercase()
            return if (FULL_SHA.matches(trimmed)) trimmed else UNKNOWN_COMMIT
        }
    }
}
