package com.emm.justchill.core.theme

import androidx.compose.ui.graphics.Color

val HhBackgroundColor = Color(0xFF020202)
val HhOnBackgroundColor = Color(0xFFFFFFFF)

val HhDisabledPrimaryButtonColor = Color(0xFF505050)
val HhPrimaryTextColor = Color(0xFF010101)
val HhSecondaryTextBackground = Color(0xFFB0B0B0)
val HhDisabledTextPrimaryBackground = Color(0xFF393939)
// card colors
val HhCardBackground = Color(0xFF171717)
val HhCardTextColor = Color(0xFFB7B7B7)


val BackgroundColor = Color(0xFF0E0519)
val BackgroundLayerColor = Color(0xFF130722)
val BackgroundLayer2Color = Color(0xFF11061E)
val InputBackgroundColor = Color(0xFF232325)
val PlaceholderOrLabel = Color(0xFF9797A0)
val TextColor = Color(0xFFE2E3E4)
val TextDisableColor = Color(0xFF7D838B)
val PrimaryButtonColor = Color(0xFF0064EB)
val PrimaryDisableButtonColor = Color(0xFF00367F)
val SecondaryButtonColor = Color(0xFF8849CD)
val DeleteButtonColor = Color(0xFFF11355)
val BorderTextFieldColor = Color(0xFF6E6973)

// Material3 builder
val primaryLightHighContrast = Color(0xFF00272C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004A53)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00272C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF004A53)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF351244)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF583467)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF44100D)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF6E302A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FAFB)
val onBackgroundLightHighContrast = Color(0xFF171D1E)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E6)
val onSurfaceVariantLightHighContrast = Color(0xFF1C2527)
val outlineLightHighContrast = Color(0xFF3B4446)
val outlineVariantLightHighContrast = Color(0xFF3B4446)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFBFF5FF)
val surfaceDimLightHighContrast = Color(0xFFD5DBDC)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF5F6)
val surfaceContainerLightHighContrast = Color(0xFFE9EFF0)
val surfaceContainerHighLightHighContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightHighContrast = Color(0xFFDEE3E5)

val primaryDarkHighContrast = Color(0xFFF1FDFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF86D7E5)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF1FDFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF86D7E5)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFE9BBF7)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB2)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E1415)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E5)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FCFE)
val outlineDarkHighContrast = Color(0xFFC3CCCE)
val outlineVariantDarkHighContrast = Color(0xFFC3CCCE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002F35)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F10)
val surfaceContainerLowDarkHighContrast = Color(0xFF171D1E)
val surfaceContainerDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303637)
