import java.io.FileInputStream
import java.util.Properties

// Generates the iOS Supabase config constants, mirroring :androidApp's buildConfigField path.
//
// Android reads root supabase.properties via buildConfigField with ""-fallbacks; iOS has no
// BuildConfig, so this generates a Kotlin constants object (IosSupabaseConfig) from the SAME root
// file into a build/ generated source dir wired into iosMain. Secrets are never hardcoded and the
// generated file lives under build/ (gitignored). When supabase.properties is absent (CI), the
// fields fall back to empty / the localhost placeholder, exactly like Android — the app stays
// usable in anonymous/offline mode. The simulator build uses the ios.* keys, falling back to dev.*.
//
// This lives in build-logic rather than in shared-ui/build.gradle.kts because it is a program, not
// a dependency declaration. Only :shared-ui applies it; the point is separation, not reuse.

plugins {
    id("org.jetbrains.kotlin.multiplatform")
}

val generatedIosConfigDir: Provider<Directory> =
    layout.buildDirectory.dir("generated/iosSupabaseConfig/kotlin")

val generateIosSupabaseConfig by tasks.registering {
    // Capture only configuration-cache-safe values (a Provider<Directory> and a File). The action
    // below must NOT reference any script-level function/property, or the configuration cache rejects
    // it ("cannot serialize Gradle script object references") — that is why the escaping helper is a
    // local fun inside doLast rather than a top-level extension.
    val outputDir = generatedIosConfigDir
    val propsFile = rootProject.file("supabase.properties")
    // Declare inputs/outputs so the task is incremental and re-runs when the properties change.
    inputs.file(propsFile).optional(true)
    outputs.dir(outputDir)
    doLast {
        // Escapes a raw value into a safe Kotlin double-quoted string literal (local to keep the
        // action self-contained / configuration-cache compatible).
        fun String.toKotlinStringLiteral(): String =
            "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}") + "\""

        val props = Properties()
        if (propsFile.exists()) {
            FileInputStream(propsFile).use { props.load(it) }
        }
        // ios.* override first, then dev.* (parity with :androidApp's dev flavor). The iOS simulator
        // shares the host network, so localhost == host; dev.supabase.url uses 10.0.2.2 (the
        // Android-emulator host alias) which the simulator cannot resolve. The ios.* override lets
        // both clients target the SAME local stack via their own alias. SUPABASE_URL keeps the empty
        // -> localhost placeholder fallback Android applies in provideSupabaseClient(); the anon key
        // falls back to dev.* (the shared local demo JWT) and stays empty only when both are absent.
        val url = props.getProperty("ios.supabase.url", "")
            .ifBlank { props.getProperty("dev.supabase.url", "") }
            .ifBlank { "http://localhost:54321" }
        val anonKey = props.getProperty("ios.supabase.anonKey", "")
            .ifBlank { props.getProperty("dev.supabase.anonKey", "") }
        val pkgDir = outputDir.get().asFile.resolve("com/emm/justchill")
        pkgDir.mkdirs()
        // String literals are escaped so quotes/backslashes in a key never break compilation.
        pkgDir.resolve("IosSupabaseConfig.kt").writeText(
            """
            |package com.emm.justchill
            |
            |// GENERATED by the generateIosSupabaseConfig Gradle task from root supabase.properties.
            |// DO NOT EDIT and DO NOT COMMIT — this file lives under build/ and is regenerated on build.
            |// iOS equivalent of Android's BuildConfig.SUPABASE_URL / SUPABASE_ANON_KEY.
            |internal object IosSupabaseConfig {
            |    const val SUPABASE_URL: String = ${url.toKotlinStringLiteral()}
            |    const val SUPABASE_ANON_KEY: String = ${anonKey.toKotlinStringLiteral()}
            |}
            |
            """.trimMargin(),
        )
    }
}

// Register the generated dir on the iOS source set. The TaskProvider (not the bare Directory
// provider) is passed on purpose: srcDir then carries the task dependency through the source set's
// declared outputs, so EVERY consumer of iosMain — Kotlin/Native compiles, detekt, detekt baseline,
// IDE sync — depends on the generator implicitly. Registering the plain directory instead makes
// Gradle 9 fail the build with "uses this output of task ':shared-ui:generateIosSupabaseConfig'
// without declaring an explicit or implicit dependency" for any consumer that lacks its own
// dependsOn (detekt hit exactly this once detektIosMainSourceSet joined the KMP gate).
//
// Registered LAZILY on purpose. `iosMain` is an intermediate source set created by the KMP default
// hierarchy template, not by the iosArm64()/iosSimulatorArm64() calls themselves, so it does not yet
// exist while this plugin is being applied — an eager getByName("iosMain") fails the build with
// "KotlinSourceSet with name 'iosMain' not found". matching {}.configureEach {} runs when the source
// set is actually realised, which is still well before any compile resolves its source dirs.
// (In the old inline form this was invisible: the block sat below the target declarations in the
// same script, so ordering happened to work.)
kotlin {
    sourceSets.matching { it.name == "iosMain" }.configureEach {
        kotlin.srcDir(generateIosSupabaseConfig)
    }
}
