complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 14
  LargeClass:
    excludes: &testSources
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/androidHostTest/**'
      - '**/androidDeviceTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  LongMethod:
    allowedLines: 60
    ignoreAnnotated: ['Composable', 'Preview', 'PreviewRedmi15C', 'PreviewRedmi15CWidth', 'PreviewWindowEdges']
  NestedBlockDepth:
    allowedDepth: 4
  TooManyFunctions:
    allowedFunctionsPerFile: 8
    ignoreAnnotatedFunctions: ['Preview', 'PreviewRedmi15C', 'PreviewRedmi15CWidth', 'PreviewWindowEdges']
    excludes: *testSources

exceptions:
  InstanceOfCheckForException:
    excludes: *testSources
  ThrowingExceptionsWithoutMessageOrCause:
    excludes: *testSources
  TooGenericExceptionCaught:
    excludes: *testSources

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
    excludes: *testSources
  MatchingDeclarationName:
    active: false

performance:
  ForEachOnRange:
    excludes: *testSources
  SpreadOperator:
    excludes: *testSources

potential-bugs:
  UnsafeCallOnNullableType:
    excludes: *testSources

style:
  MagicNumber:
    ignoreAnnotated: ['Preview', 'PreviewRedmi15C', 'PreviewRedmi15CWidth', 'PreviewWindowEdges']
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/androidHostTest/**', '**/androidDeviceTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts']
  ReturnCount:
    max: 2
    excludeReturnFromLambda: true

Compose:
  CompositionLocalAllowlist:
    allowedCompositionLocals:
      - 'LocalEmmColors'
      - 'LocalEmmRadii'
      - 'LocalEmmSpacing'
      - 'LocalEmmType'
