name: Upload to Play Store

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  upload_to_playstore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Create keystore.properties file
        run: echo "${{ secrets.JUST_VERONICA }}" > keystore.properties

      - name: JUST CHILL
        run: |
          mkdir -p key
          echo "${{ secrets.JUST_CHILL }}" | base64 --decode > key/just_chill_key.p12

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release
        run: ./gradlew bundleProdRelease

      - name: Upload AAB Prod Release
        uses: actions/upload-artifact@v4
        with:
          name: AAB(s) prod release
          path: app/build/outputs/bundle/prodRelease/

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.emm.justchill
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          status: draft
          track: internal